# version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0 #自带 linux/arm64 镜像
    container_name: ws-design-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_2026
      MYSQL_DATABASE: ws_design_db
      MYSQL_USER: ws_design
      MYSQL_PASSWORD: ws_design_2026
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # NestJS 后端服务
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ws-design-server
    restart: always
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "mysql://ws_design:ws_design_2026@mysql:3306/ws_design_db"
      JWT_SECRET: "ws-design-jwt-secret-key-2026"
      PORT: "3000"
    depends_on:
      - mysql

volumes:
  mysql_data:
